variable "ssh_key_name_prefix" {
  description = "Key name prefix for ssh rsa public key"
  default = "terraform-"
}

variable "ssh_public_key_path" {
  description = "Path to ssh rsa public key"
  default = "~/.ssh/id_rsa.pub"
}

variable "iam_role_name" {
  description = "The name of the IAM Role."
}

variable "iam_role_path" {
  description = "The path to the IAM Role."
  default     = "/"
}

variable "iam_role_description" {
  description = "The description of the IAM Role."
  default     = "This IAM Role generated by Terraform."
}

variable "iam_role_force_detach_policies" {
  description = "Forcibly detach the policy of the role."
  default     = false
}

variable "iam_role_policy_arn" {
  description = "Attache the policies to the IAM Role."
  type        = "list"
}
